name: nginx-proxy
services:
  customer:
    build:
      context: ./CustomerApi  
      dockerfile: Dockerfile 
    container_name: customer   
    ports:
      - "5000:80"
    command: ["dotnet", "CustomerApi.dll"]
    stdin_open: true 
    tty: true      
    networks:
      - laboratory-nginx

networks:
  laboratory-nginx: 
    driver: bridge